-- Harden course video access for member-area playback.
-- Videos are served through signed URLs generated by backend checks.

update storage.buckets
set public = false
where id = 'course-videos';

drop policy if exists "public can read course videos" on storage.objects;

drop policy if exists "admins can read course videos" on storage.objects;
create policy "admins can read course videos"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'course-videos' and public.is_mktbr_admin());
